export const AppConfig = {
  name: 'SYMBIODROID',
  version: '1.0.0',
  buildNumber: '001',
  agentName: 'OMEGA',
  maxMemoryEntries: 100,
  omegaGateBannedTerms: [
    'format disk', 'delete all', 'steal', 'malware',
    'hack', 'exploit', 'bypass security', 'rm -rf',
  ],
};

export const SkillsConfig = [
  {
    id: 'coding',
    name: 'OmegaCoder',
    icon: 'code-slash',
    description: 'Analisa, gera e corrige código automaticamente',
    category: 'Desenvolvimento',
    status: 'active',
    color: '#00FF94',
    uses: 147,
  },
  {
    id: 'vault',
    name: 'Vault Guard',
    icon: 'shield-checkmark',
    description: 'Armazenamento soberano criptografado',
    category: 'Segurança',
    status: 'active',
    color: '#FFD700',
    uses: 83,
  },
  {
    id: 'founder',
    name: 'Founder Copilot',
    icon: 'rocket',
    description: 'Estratégia, análise e decisões de startup',
    category: 'Negócios',
    status: 'active',
    color: '#8B5CF6',
    uses: 62,
  },
  {
    id: 'twin',
    name: 'Twin Firewall',
    icon: 'eye-off',
    description: 'Detecta clonagem de identidade e uso não autorizado da pessoa digital',
    category: 'Segurança',
    status: 'beta',
    color: '#FF4444',
    uses: 12,
  },
  {
    id: 'consent',
    name: 'Consent Engine',
    icon: 'document-lock',
    description: 'Contratos programáveis de consentimento, acesso e revogação',
    category: 'Segurança',
    status: 'beta',
    color: '#8B5CF6',
    uses: 7,
  },
  {
    id: 'forensic',
    name: 'Forensic Agent',
    icon: 'search',
    description: 'Análise profunda de dados e auditoria',
    category: 'Análise',
    status: 'beta',
    color: '#00E5FF',
    uses: 29,
  },
  {
    id: 'mesh',
    name: 'Offline Mesh',
    icon: 'wifi',
    description: 'Operação soberana sem internet',
    category: 'Infraestrutura',
    status: 'coming',
    color: '#FF8C00',
    uses: 0,
  },
  {
    id: 'drone',
    name: 'Drone Mode',
    icon: 'airplane',
    description: 'Automação autônoma de tarefas complexas',
    category: 'Automação',
    status: 'coming',
    color: '#FF4444',
    uses: 0,
  },
];

export const SkillsConfig2 = [
  {
    id: 'twin-firewall',
    name: 'Twin Firewall',
    icon: 'eye-off',
    description: 'Detecta e bloqueia uso não autorizado de identidade e clonagem digital',
    category: 'Segurança',
    status: 'beta',
    color: '#FF4444',
    uses: 12,
  },
  {
    id: 'consent-engine',
    name: 'Consent Engine',
    icon: 'document-lock',
    description: 'Contratos programáveis de consentimento e revogação de acesso',
    category: 'Segurança',
    status: 'beta',
    color: '#8B5CF6',
    uses: 7,
  },
];

export const LegacyPolicies = [
  {
    id: 'allow_training',
    label: 'Permitir treino de IA com meus dados',
    description: 'Sistemas de IA podem usar seu rastro digital para treinar modelos',
    risk: 'high',
    defaultValue: false,
  },
  {
    id: 'allow_avatar',
    label: 'Permitir avatar póstumo',
    description: 'Reconstrução de voz, imagem e estilo comunicacional após morte',
    risk: 'high',
    defaultValue: false,
  },
  {
    id: 'allow_posthumous_use',
    label: 'Uso comercial póstumo',
    description: 'Empresas podem usar sua identidade digital para fins comerciais',
    risk: 'high',
    defaultValue: false,
  },
  {
    id: 'allow_family_access',
    label: 'Acesso familiar ao vault',
    description: 'Herdeiros designados podem acessar vault após confirmação legal',
    risk: 'medium',
    defaultValue: false,
  },
  {
    id: 'allow_research',
    label: 'Uso em pesquisa acadêmica',
    description: 'Instituições de pesquisa podem analisar dados anonimizados',
    risk: 'low',
    defaultValue: false,
  },
  {
    id: 'revoke_all',
    label: 'Revogar tudo por padrão',
    description: 'Nenhum sistema externo pode acessar ou usar sua identidade digital',
    risk: 'none',
    defaultValue: true,
  },
];

export const ConsentContracts = [
  {
    id: 'c1',
    entity: 'OmegaCoder Engine',
    scope: 'Execução de código local',
    status: 'active',
    granted: Date.now() - 2592000000,
    expiry: Date.now() + 31536000000,
    revocable: true,
  },
  {
    id: 'c2',
    entity: 'Vault Guard Service',
    scope: 'Acesso ao vault criptografado',
    status: 'active',
    granted: Date.now() - 5184000000,
    expiry: null,
    revocable: true,
  },
  {
    id: 'c3',
    entity: 'Analytics Local',
    scope: 'Métricas de uso anonimizadas',
    status: 'paused',
    granted: Date.now() - 864000000,
    expiry: null,
    revocable: true,
  },
];

export const QuickActions = [
  { id: 'code', label: 'Código', icon: 'code-slash', prompt: 'Analisar e melhorar meu código' },
  { id: 'plan', label: 'Planejar', icon: 'map', prompt: 'Criar um plano estratégico' },
  { id: 'vault', label: 'Vault', icon: 'lock-closed', prompt: 'Acessar vault seguro' },
  { id: 'analyze', label: 'Analisar', icon: 'analytics', prompt: 'Analisar dados e gerar insights' },
];
